# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Kendra Walker
email: ""
description: >- # this means to ignore newlines until "baseurl:"
  I am an applied scientist with a passion for exploring complex social-ecological problems through 
  multilayered analysis and innovative tool-building. My work focuses on agriculture and forest-based
  systems and the decision making at individual and institutional levels that influences these systems.
  I make extensive use of remote sensing, machine learning, and GIS to identify trends in land use change
  and couple these with tools including impact evaluation, cost-benefit analysis, agent-based modeling,
  and on-the-ground interviews to help understand drivers and the decision making behind these processes.  
baseurl: "/klwalker-sb"
url: "https://klwalker-sb.github.io"
twitter_username: 
github_username:  klwalker-sb

# Build settings
# removed minima theme -- now using cayman as a regular theme
# theme: minima
# remote_theme: "pages-themes/cayman@v0.2.0"
plugins:
  # - jekyll-feed
  - jekyll-remote-theme
# turning off `view source code` button
github:
  is_project_page: false 
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
